export const defaultCategories = [
  {
    "id": 1,
    "name": "Breakfast",
    "slug": "breakfast",
    "icon": "sunrise",
    "sort_order": 0
  },
  {
    "id": 2,
    "name": "Lunch",
    "slug": "lunch",
    "icon": "curry",
    "sort_order": 1
  },
  {
    "id": 3,
    "name": "Evening Snacks",
    "slug": "evening-snacks",
    "icon": "starter",
    "sort_order": 2
  },
  {
    "id": 4,
    "name": "Dinner",
    "slug": "dinner",
    "icon": "dosa",
    "sort_order": 3
  }
];

export const defaultItems = [
  {
    "id": 1,
    "category_id": 1,
    "name": "Idly",
    "description": "Steamed rice cakes, soft and fluffy, served with sambar & chutney",
    "price": 40,
    "image": "/images/kinds/idly.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 2,
    "category_id": 1,
    "name": "Sambar Idly",
    "description": "Idly soaked in piping hot sambar",
    "price": 50,
    "image": "/images/kinds/sambarIdly.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 3,
    "category_id": 1,
    "name": "Vadai",
    "description": "Crispy golden lentil doughnuts",
    "price": 40,
    "image": "/images/kinds/vada.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 4,
    "category_id": 1,
    "name": "Sambar Vadai",
    "description": "Crispy vadai dunked in sambar",
    "price": 50,
    "image": "/images/kinds/sambarVada.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 5,
    "category_id": 1,
    "name": "Pongal",
    "description": "Comforting rice & moong dal porridge tempered with pepper and cumin",
    "price": 60,
    "image": "/images/kinds/pongalKichadi.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 6,
    "category_id": 1,
    "name": "Poori Masal",
    "description": "Puffed fried bread served with spiced potato masal",
    "price": 70,
    "image": "/images/kinds/poori.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 7,
    "category_id": 1,
    "name": "Kichadi",
    "description": "Semolina & vegetable kichadi",
    "price": 50,
    "image": "/images/kinds/kichadi.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 8,
    "category_id": 1,
    "name": "Sevai",
    "description": "Steamed rice noodles, lightly tempered",
    "price": 50,
    "image": "/images/kinds/sevai.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 7,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 9,
    "category_id": 1,
    "name": "Roast",
    "description": "Classic crisp roasted dosa",
    "price": 60,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 8,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 10,
    "category_id": 1,
    "name": "Onion Roast",
    "description": "Roasted dosa topped with fresh onions",
    "price": 70,
    "image": "/images/kinds/dosaOnion.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 9,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 11,
    "category_id": 1,
    "name": "Masal Roast",
    "description": "Roast dosa filled with spiced potato masala",
    "price": 80,
    "image": "/images/kinds/dosaStuffed.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 10,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 12,
    "category_id": 1,
    "name": "Ghee Roast",
    "description": "Roast dosa finished with pure ghee",
    "price": 80,
    "image": "/images/kinds/dosaGhee.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 11,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 13,
    "category_id": 1,
    "name": "Onion Rava Roast",
    "description": "Crispy semolina roast loaded with onions",
    "price": 90,
    "image": "/images/kinds/dosaRavaOnion.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 12,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 14,
    "category_id": 1,
    "name": "Ghee Masal Roast",
    "description": "Ghee roast filled with potato masala",
    "price": 100,
    "image": "/images/kinds/ghee_masal_roast_1786192387372.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 13,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 15,
    "category_id": 1,
    "name": "Cashewnut Rava Roast",
    "description": "Semolina roast topped with roasted cashews",
    "price": 110,
    "image": "/images/kinds/dosaRava.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 14,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 16,
    "category_id": 1,
    "name": "Uthappam",
    "description": "Thick savoury rice pancake",
    "price": 70,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 15,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 17,
    "category_id": 1,
    "name": "Onion Uthappam",
    "description": "Uthappam topped with onions",
    "price": 80,
    "image": "/images/kinds/uthappamOnion.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 16,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 18,
    "category_id": 1,
    "name": "Tomato Uthappam",
    "description": "Uthappam topped with tomatoes",
    "price": 80,
    "image": "/images/kinds/uthappamTomato.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 17,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 19,
    "category_id": 1,
    "name": "Podi Uthappam",
    "description": "Uthappam with spiced gunpowder podi",
    "price": 80,
    "image": "/images/kinds/uthappamPodi.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 18,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 20,
    "category_id": 1,
    "name": "Ghee Uthappam",
    "description": "Uthappam finished with ghee",
    "price": 90,
    "image": "/images/kinds/uthappamGhee.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 19,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 21,
    "category_id": 1,
    "name": "Veg. Uthappam",
    "description": "Mixed vegetable topped uthappam",
    "price": 90,
    "image": "/images/kinds/uthappamVeg.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 20,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 22,
    "category_id": 1,
    "name": "Chappathi",
    "description": "Soft whole-wheat flatbread (2 pcs) with kurma",
    "price": 60,
    "image": "/images/kinds/chappathi.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 21,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 23,
    "category_id": 1,
    "name": "Onion Chappathi",
    "description": "Chappathi stuffed with onions",
    "price": 70,
    "image": "/images/kinds/onion_chappathi_1786192404575.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 22,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 24,
    "category_id": 1,
    "name": "Parotta",
    "description": "Layered, flaky Kerala-style parotta (2 pcs)",
    "price": 60,
    "image": "/images/kinds/parotta.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 23,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 25,
    "category_id": 1,
    "name": "Kal Dosai",
    "description": "Thick, soft, slightly fermented dosa",
    "price": 70,
    "image": "/images/kinds/dosaKal.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 24,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 26,
    "category_id": 1,
    "name": "Elan Dosai",
    "description": "Traditional soft, fragrant tender coconut infused dosa",
    "price": 70,
    "image": "/images/kinds/dosaElai.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 25,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 27,
    "category_id": 3,
    "name": "Veg. Clear Soup",
    "description": "Light and clear mixed vegetable soup",
    "price": 70,
    "image": "/images/kinds/soupClear.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 26,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 28,
    "category_id": 3,
    "name": "Tomato Soup",
    "description": "Classic creamy tomato soup",
    "price": 70,
    "image": "/images/kinds/soup.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 27,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 29,
    "category_id": 3,
    "name": "Sweet Corn Soup",
    "description": "Sweet corn kernels in a mild veg broth",
    "price": 80,
    "image": "/images/kinds/soupCorn.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 28,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 30,
    "category_id": 3,
    "name": "Mushroom Soup",
    "description": "Earthy mushroom soup, velvety texture",
    "price": 90,
    "image": "/images/kinds/soupMushroom.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 29,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 31,
    "category_id": 3,
    "name": "Veg. Cutlet",
    "description": "Crumb-fried mixed vegetable cutlets",
    "price": 100,
    "image": "/images/kinds/cutlet.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 30,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 32,
    "category_id": 3,
    "name": "Finger Chips",
    "description": "Crispy golden potato fingers",
    "price": 90,
    "image": "/images/kinds/fingerChips.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 31,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 33,
    "category_id": 3,
    "name": "Paneer Pakoda",
    "description": "Deep fried gram-flour battered paneer fritters",
    "price": 130,
    "image": "/images/kinds/pakoda.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 32,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 34,
    "category_id": 3,
    "name": "Gobi 65",
    "description": "Spicy, tangy deep fried cauliflower florets",
    "price": 110,
    "image": "/images/kinds/gobi65.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 33,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 35,
    "category_id": 3,
    "name": "Mushroom 65",
    "description": "Crispy spiced deep fried mushrooms",
    "price": 130,
    "image": "/images/kinds/mushroom65.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 34,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 36,
    "category_id": 3,
    "name": "Tomato Fry",
    "description": "Pan tossed spiced tomato fry",
    "price": 90,
    "image": "/images/kinds/tomatoFry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 35,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 37,
    "category_id": 3,
    "name": "Masala Papad",
    "description": "Crisp papad topped with onion-tomato masala",
    "price": 60,
    "image": "/images/kinds/papad.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 36,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 38,
    "category_id": 1,
    "name": "Kuzhi Paniyaram",
    "description": "Steamed-fried savoury rice & lentil dumplings",
    "price": 90,
    "image": "/images/kinds/paniyaram.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 37,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 39,
    "category_id": 1,
    "name": "Idiyappam & Appam",
    "description": "String hoppers and appam served together",
    "price": 90,
    "image": "/images/kinds/idiyappamAppam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 38,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 40,
    "category_id": 3,
    "name": "Gobi Manchurian",
    "description": "Cauliflower florets tossed in tangy manchurian sauce",
    "price": 120,
    "image": "/images/kinds/manchurian.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 39,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 41,
    "category_id": 3,
    "name": "Chilly Gobi",
    "description": "Cauliflower tossed with chilli, capsicum & onion",
    "price": 120,
    "image": "/images/kinds/chilly_gobi_1786192418596.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 40,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 42,
    "category_id": 3,
    "name": "Chilly Paneer",
    "description": "Paneer cubes tossed in spicy Indo-Chinese sauce",
    "price": 150,
    "image": "/images/kinds/chillyPaneer.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 41,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 43,
    "category_id": 3,
    "name": "Chilly Mushroom",
    "description": "Mushrooms tossed in spicy chilli-garlic sauce",
    "price": 140,
    "image": "/images/kinds/chillyMushroom.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 42,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 44,
    "category_id": 3,
    "name": "Soft Noodles",
    "description": "Wok tossed veg noodles",
    "price": 120,
    "image": "/images/kinds/noodles.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 43,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 45,
    "category_id": 3,
    "name": "Veg. Spl. Briyani (Chinese style)",
    "description": "Indo-Chinese style spiced veg biryani",
    "price": 150,
    "image": "/images/kinds/biryaniChinese.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 44,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 46,
    "category_id": 3,
    "name": "Chinees Briyani",
    "description": "Fragrant rice tossed with Chinese-style vegetables",
    "price": 150,
    "image": "/images/kinds/chinese_biryani_1786192433353.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 45,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 47,
    "category_id": 2,
    "name": "Paneer Butter Masala",
    "description": "Paneer cubes in a rich buttery tomato gravy",
    "price": 170,
    "image": "/images/kinds/curryPaneerButter.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 46,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 48,
    "category_id": 2,
    "name": "Green Peas Masala",
    "description": "Green peas simmered in a spiced onion-tomato gravy",
    "price": 130,
    "image": "/images/kinds/green_peas_masala_1786192448892.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 47,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 49,
    "category_id": 2,
    "name": "Gobi Masala",
    "description": "Cauliflower cooked in a mildly spiced curry",
    "price": 130,
    "image": "/images/kinds/gobi_masala_1786192465068.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 48,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 50,
    "category_id": 2,
    "name": "Aloo Gobi Masala",
    "description": "Potato & cauliflower cooked with aromatic spices",
    "price": 130,
    "image": "/images/kinds/aloo_gobi_masala_1786192482220.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 49,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 51,
    "category_id": 2,
    "name": "Mushroom Masala",
    "description": "Mushrooms in a spiced curry gravy",
    "price": 140,
    "image": "/images/kinds/curryMushroom.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 50,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 52,
    "category_id": 2,
    "name": "Cheese Masala",
    "description": "Cottage cheese cubes in a creamy masala gravy",
    "price": 160,
    "image": "/images/kinds/cheese_masala_1786192498948.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 51,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 53,
    "category_id": 2,
    "name": "Malai Kofta",
    "description": "Fried vegetable & paneer dumplings in a creamy gravy",
    "price": 170,
    "image": "/images/kinds/curryMalaiKofta.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 52,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 54,
    "category_id": 2,
    "name": "Mix. Veg Curry",
    "description": "Seasonal vegetables cooked in a mild curry",
    "price": 130,
    "image": "/images/kinds/curryVeg.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 53,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 55,
    "category_id": 2,
    "name": "Butter Paneer Masala",
    "description": "Paneer in a velvety butter-tomato gravy",
    "price": 180,
    "image": "/images/kinds/butter_paneer_masala_1786192514966.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 54,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 56,
    "category_id": 2,
    "name": "Aloo Butter Masala",
    "description": "Potatoes cooked in a rich buttery gravy",
    "price": 140,
    "image": "/images/kinds/aloo_butter_masala_1786192529374.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 55,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 57,
    "category_id": 2,
    "name": "Naan",
    "description": "Soft, pillowy tandoor-baked leavened bread",
    "price": 50,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 56,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 58,
    "category_id": 2,
    "name": "Butter Naan",
    "description": "Naan brushed with butter",
    "price": 60,
    "image": "/images/kinds/naanButter.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 57,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 59,
    "category_id": 2,
    "name": "Roti",
    "description": "Whole wheat tandoor bread",
    "price": 40,
    "image": "/images/kinds/roti.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 58,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 60,
    "category_id": 2,
    "name": "Romali Roti",
    "description": "Ultra-thin soft handkerchief bread",
    "price": 50,
    "image": "/images/kinds/romaliRoti.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 59,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 61,
    "category_id": 2,
    "name": "Chola Poori",
    "description": "Fluffy fried poori served with chickpea masala",
    "price": 90,
    "image": "/images/kinds/cholaPoori.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 60,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 62,
    "category_id": 2,
    "name": "Veg. Fried Rice",
    "description": "Wok tossed rice with fresh vegetables",
    "price": 110,
    "image": "/images/kinds/friedRice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 61,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 63,
    "category_id": 2,
    "name": "Veg. Pulao",
    "description": "Fragrant basmati rice cooked with mixed vegetables",
    "price": 120,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 62,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 64,
    "category_id": 2,
    "name": "Peas Pulao",
    "description": "Basmati rice cooked with green peas",
    "price": 120,
    "image": "/images/kinds/peas_pulao_1786192546936.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 63,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 65,
    "category_id": 2,
    "name": "Jeera Pulao",
    "description": "Basmati rice tempered with cumin",
    "price": 110,
    "image": "/images/kinds/jeera_pulao_1786192562226.png",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 64,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 66,
    "category_id": 2,
    "name": "Mushroom Pulao",
    "description": "Basmati rice cooked with mushrooms",
    "price": 140,
    "image": "/images/items/66.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 65,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 67,
    "category_id": 2,
    "name": "Kashmir Pulao",
    "description": "Mildly sweet pulao with fruits & nuts",
    "price": 150,
    "image": "/images/items/67.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 66,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 68,
    "category_id": 2,
    "name": "Veg. Briyani",
    "description": "Classic spiced vegetable dum biryani",
    "price": 150,
    "image": "/images/kinds/biryani.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 67,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 69,
    "category_id": 2,
    "name": "Mushroom Briyani",
    "description": "Aromatic dum biryani with mushrooms",
    "price": 160,
    "image": "/images/items/69.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 68,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 70,
    "category_id": 2,
    "name": "Curd Rice",
    "description": "Comforting curd rice tempered with mustard & curry leaves",
    "price": 80,
    "image": "/images/kinds/curdRice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 69,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 71,
    "category_id": 2,
    "name": "Curd Semia",
    "description": "Vermicelli tossed in seasoned curd",
    "price": 80,
    "image": "/images/kinds/curdSemia.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 70,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 72,
    "category_id": 2,
    "name": "Variety Rices",
    "description": "Assorted South Indian tamarind / lemon / coconut rice",
    "price": 90,
    "image": "/images/kinds/varietyRice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 71,
    "is_breakfast": false,
    "is_lunch": true,
    "is_snacks": false,
    "is_dinner": false
  },
  {
    "id": 73,
    "category_id": 3,
    "name": "Cauliflower Roast",
    "description": "Whole roasted cauliflower in spiced masala",
    "price": 140,
    "image": "/images/items/73.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 72,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 74,
    "category_id": 3,
    "name": "Mushroom Roast",
    "description": "Pan roasted mushrooms in dry masala",
    "price": 150,
    "image": "/images/items/74.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 73,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 75,
    "category_id": 3,
    "name": "Paneer Masal Roast",
    "description": "Paneer roasted in a dry spiced masala",
    "price": 170,
    "image": "/images/kinds/paneerRoast.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 74,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 76,
    "category_id": 3,
    "name": "Green Peas Masal Roast",
    "description": "Green peas roasted in a dry spiced masala",
    "price": 130,
    "image": "/images/items/76.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 75,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 77,
    "category_id": 1,
    "name": "Set Dosa (Monday Special)",
    "description": "Soft mini dosas served in a stack of three",
    "price": 80,
    "image": "/images/kinds/dosaSet.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 76,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 78,
    "category_id": 1,
    "name": "Peas Uthappam (Tuesday Special)",
    "description": "Uthappam topped with green peas",
    "price": 90,
    "image": "/images/kinds/uthappamPeas.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 77,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 79,
    "category_id": 1,
    "name": "Five Taste Uthappam (Wednesday Special)",
    "description": "Uthappam topped with five signature toppings",
    "price": 100,
    "image": "/images/kinds/uthappamFiveTaste.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 78,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 80,
    "category_id": 1,
    "name": "Vanilla Roast (Thursday Special)",
    "description": "Signature house roast dosa",
    "price": 90,
    "image": "/images/kinds/dosaVanilla.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 79,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 81,
    "category_id": 1,
    "name": "Adai - Aviyal (Friday Special)",
    "description": "Multi-lentil adai served with mixed vegetable aviyal",
    "price": 100,
    "image": "/images/kinds/adaiAviyal.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 80,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 82,
    "category_id": 1,
    "name": "Chenna Masal Roast (Saturday Special)",
    "description": "Roast dosa filled with spiced chenna masala",
    "price": 100,
    "image": "/images/items/82.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 81,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 83,
    "category_id": 1,
    "name": "Veg Omelette (Sunday Special)",
    "description": "Besan-based vegetarian omelette",
    "price": 90,
    "image": "/images/kinds/vegOmelette.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 82,
    "is_breakfast": true,
    "is_lunch": false,
    "is_snacks": false,
    "is_dinner": true
  },
  {
    "id": 84,
    "category_id": 3,
    "name": "Chilly Parotta",
    "description": "Shredded parotta tossed with chilli & spices",
    "price": 130,
    "image": "/images/kinds/chillyParotta.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": true,
    "sort_order": 83,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 85,
    "category_id": 3,
    "name": "Chilly Idly",
    "description": "Cubed idly tossed in spicy chilli sauce",
    "price": 100,
    "image": "/images/kinds/chillyIdly.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": true,
    "sort_order": 84,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 86,
    "category_id": 3,
    "name": "Kaima Parotta",
    "description": "Parotta tossed with a rich, minced-vegetable style kaima masala",
    "price": 140,
    "image": "/images/items/24.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 85,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 87,
    "category_id": 3,
    "name": "Peas Parotta",
    "description": "Shredded parotta tossed with green peas masala",
    "price": 130,
    "image": "/images/items/87.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 86,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 88,
    "category_id": 3,
    "name": "Idly Fry",
    "description": "Pan fried idly tossed with spices",
    "price": 90,
    "image": "/images/kinds/idlyFry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 87,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 89,
    "category_id": 3,
    "name": "Gobi Fry",
    "description": "Dry roasted spiced cauliflower fry",
    "price": 110,
    "image": "/images/kinds/roastDry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 88,
    "is_breakfast": false,
    "is_lunch": false,
    "is_snacks": true,
    "is_dinner": false
  },
  {
    "id": 90,
    "category_id": 1,
    "name": "Bournvita",
    "description": "Hot malted chocolate drink",
    "price": 50,
    "image": "/images/kinds/hotDrink.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 89,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 91,
    "category_id": 1,
    "name": "Ragimalt",
    "description": "Traditional finger-millet health drink",
    "price": 60,
    "image": "/images/items/91.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 90,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 92,
    "category_id": 1,
    "name": "Lemon Tea",
    "description": "Refreshing hot lemon tea",
    "price": 40,
    "image": "/images/kinds/lemonTea.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 91,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 93,
    "category_id": 1,
    "name": "Sukku Coffee",
    "description": "Traditional dry ginger coffee",
    "price": 50,
    "image": "/images/items/7.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 92,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 94,
    "category_id": 1,
    "name": "Kalkandu Milk",
    "description": "Milk sweetened with rock candy",
    "price": 60,
    "image": "/images/kinds/coldDrink.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 93,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 95,
    "category_id": 1,
    "name": "Badam Milk",
    "description": "Chilled milk infused with almonds & saffron",
    "price": 80,
    "image": "/images/items/3.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 94,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 96,
    "category_id": 1,
    "name": "Mini Cone",
    "description": "Bite sized crunchy cone",
    "price": 30,
    "image": "/images/items/96.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 95,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 97,
    "category_id": 1,
    "name": "Suvai Ball",
    "description": "Classic ice cream ball",
    "price": 40,
    "image": "/images/items/97.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 96,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 98,
    "category_id": 1,
    "name": "Sunday Sundae",
    "description": "Layered sundae with toppings",
    "price": 90,
    "image": "/images/kinds/sundae.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 97,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 99,
    "category_id": 1,
    "name": "Cassata Slice",
    "description": "Tri-colour cassata ice cream slice",
    "price": 60,
    "image": "/images/kinds/iceCreamCassata.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 98,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 100,
    "category_id": 1,
    "name": "Malai Kulfi",
    "description": "Traditional creamy malai kulfi",
    "price": 60,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 99,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 101,
    "category_id": 1,
    "name": "Super Cone",
    "description": "Large classic ice cream cone",
    "price": 50,
    "image": "/images/kinds/iceCreamCone.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 100,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 102,
    "category_id": 1,
    "name": "Premium Cassata",
    "description": "Rich premium cassata ice cream",
    "price": 80,
    "image": "/images/items/102.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 101,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 103,
    "category_id": 1,
    "name": "Amrit Kalash Kulfi",
    "description": "Signature rich dry-fruit kulfi",
    "price": 90,
    "image": "/images/items/100.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 102,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 104,
    "category_id": 1,
    "name": "Italian's Touch",
    "description": "Italian style gourmet ice cream",
    "price": 100,
    "image": "/images/items/104.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 103,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 105,
    "category_id": 1,
    "name": "Melting Moments",
    "description": "Soft melt-in-mouth ice cream treat",
    "price": 80,
    "image": "/images/items/105.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 104,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 106,
    "category_id": 1,
    "name": "Phata Phat",
    "description": "Fun crackling-topped ice cream novelty",
    "price": 70,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 105,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 107,
    "category_id": 1,
    "name": "Choc-O-Bar",
    "description": "Classic chocolate coated vanilla stick",
    "price": 40,
    "image": "/images/kinds/chocobar.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 106,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 108,
    "category_id": 1,
    "name": "Mini Chocobar",
    "description": "Bite sized chocolate coated stick",
    "price": 25,
    "image": "/images/items/108.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 107,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 109,
    "category_id": 1,
    "name": "Nutty Chocobar",
    "description": "Chocolate coated stick with crunchy nuts",
    "price": 50,
    "image": "/images/items/109.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 108,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 110,
    "category_id": 1,
    "name": "Mango Duo",
    "description": "Two layered mango ice cream stick",
    "price": 45,
    "image": "/images/kinds/fruitStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 109,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 111,
    "category_id": 1,
    "name": "Raspberry Duo",
    "description": "Two layered raspberry ice cream stick",
    "price": 45,
    "image": "/images/items/111.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 110,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 112,
    "category_id": 1,
    "name": "Orange Duo",
    "description": "Two layered orange ice cream stick",
    "price": 45,
    "image": "/images/items/110.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 111,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 113,
    "category_id": 1,
    "name": "Fiesta",
    "description": "Colourful fruit-flavoured ice cream stick",
    "price": 50,
    "image": "/images/items/113.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 112,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 114,
    "category_id": 1,
    "name": "Cassatta",
    "description": "Classic tri-flavour ice cream",
    "price": 60,
    "image": "/images/items/114.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 113,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 115,
    "category_id": 1,
    "name": "Vanilla",
    "description": "Rich and creamy vanilla ice cream",
    "price": 50,
    "image": "/images/kinds/iceCreamVanilla.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 114,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 116,
    "category_id": 1,
    "name": "Strawberry",
    "description": "Fresh strawberry ice cream",
    "price": 55,
    "image": "/images/kinds/iceCreamStrawberry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 115,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 117,
    "category_id": 1,
    "name": "Pista Green",
    "description": "Roasted pistachio ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamPistachio.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 116,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 118,
    "category_id": 1,
    "name": "Mango",
    "description": "Seasonal mango ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamMango.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 117,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 119,
    "category_id": 1,
    "name": "Chocolate",
    "description": "Rich Belgian style chocolate ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamChocolate.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 118,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 120,
    "category_id": 1,
    "name": "Butter Scotch",
    "description": "Caramelised butterscotch ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamButterscotch.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 119,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  },
  {
    "id": 121,
    "category_id": 1,
    "name": "Black Currant",
    "description": "Tangy black currant ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamBlackCurrant.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 120,
    "is_breakfast": true,
    "is_lunch": true,
    "is_snacks": true,
    "is_dinner": true
  }
];

export const defaultSettings = {
  "id": 1,
  "restaurant_name": "Amutha Surabi Restaurant",
  "tagline": "Experience Authentic Taste",
  "logo": "",
  "banner": "",
  "address": "8A, Thadagam Main Road, Edayar Palayam Junction, Coimbatore - 25",
  "phone": "",
  "opening_hours": "7:30 AM - 10:30 PM",
  "facebook": "",
  "instagram": "",
  "whatsapp": "",
  "theme_primary": "#D4AF37",
  "theme_dark": "#0B0B0F",
  "menu_url": "http://localhost:5173"
};
