export const defaultCategories = [
  {
    "id": 1,
    "name": "Breakfast",
    "slug": "breakfast",
    "icon": "sunrise",
    "sort_order": 0
  },
  {
    "id": 2,
    "name": "Tiffin & Dosa Varieties",
    "slug": "tiffin-dosa-varieties",
    "icon": "dosa",
    "sort_order": 1
  },
  {
    "id": 3,
    "name": "Soups",
    "slug": "soups",
    "icon": "soup",
    "sort_order": 2
  },
  {
    "id": 4,
    "name": "Veg Starters",
    "slug": "veg-starters",
    "icon": "starter",
    "sort_order": 3
  },
  {
    "id": 5,
    "name": "Chinese",
    "slug": "chinese",
    "icon": "chinese",
    "sort_order": 4
  },
  {
    "id": 6,
    "name": "North Indian Curry",
    "slug": "north-indian-curry",
    "icon": "curry",
    "sort_order": 5
  },
  {
    "id": 7,
    "name": "Breads",
    "slug": "breads",
    "icon": "bread",
    "sort_order": 6
  },
  {
    "id": 8,
    "name": "Biryani & Rice",
    "slug": "biryani-rice",
    "icon": "biryani",
    "sort_order": 7
  },
  {
    "id": 9,
    "name": "Roast Specials",
    "slug": "roast-specials",
    "icon": "roast",
    "sort_order": 8
  },
  {
    "id": 10,
    "name": "Weekly Specials",
    "slug": "weekly-specials",
    "icon": "calendar",
    "sort_order": 9
  },
  {
    "id": 11,
    "name": "House Specials",
    "slug": "house-specials",
    "icon": "star",
    "sort_order": 10
  },
  {
    "id": 12,
    "name": "Health Beverages",
    "slug": "health-beverages",
    "icon": "cup",
    "sort_order": 11
  },
  {
    "id": 13,
    "name": "Ice Cream Novelties",
    "slug": "ice-cream-novelties",
    "icon": "icecream",
    "sort_order": 12
  },
  {
    "id": 14,
    "name": "Ice Cream Sticks",
    "slug": "ice-cream-sticks",
    "icon": "stick",
    "sort_order": 13
  },
  {
    "id": 15,
    "name": "Ice Cream Flavours",
    "slug": "ice-cream-flavours",
    "icon": "scoop",
    "sort_order": 14
  }
];

export const defaultItems = [
  {
    "id": 1,
    "category_id": 1,
    "name": "Idly",
    "description": "Steamed rice cakes, soft and fluffy, served with sambar & chutney",
    "price": 40,
    "image": "/images/kinds/idly.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 2,
    "category_id": 1,
    "name": "Sambar Idly",
    "description": "Idly soaked in piping hot sambar",
    "price": 50,
    "image": "/images/kinds/idly.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 3,
    "category_id": 1,
    "name": "Vadai",
    "description": "Crispy golden lentil doughnuts",
    "price": 40,
    "image": "/images/kinds/vada.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 4,
    "category_id": 1,
    "name": "Sambar Vadai",
    "description": "Crispy vadai dunked in sambar",
    "price": 50,
    "image": "/images/kinds/vada.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 5,
    "category_id": 1,
    "name": "Pongal",
    "description": "Comforting rice & moong dal porridge tempered with pepper and cumin",
    "price": 60,
    "image": "/images/kinds/pongalKichadi.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 6,
    "category_id": 1,
    "name": "Poori Masal",
    "description": "Puffed fried bread served with spiced potato masal",
    "price": 70,
    "image": "/images/kinds/poori.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 7,
    "category_id": 1,
    "name": "Kichadi",
    "description": "Semolina & vegetable kichadi",
    "price": 50,
    "image": "/images/kinds/pongalKichadi.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 8,
    "category_id": 1,
    "name": "Sevai",
    "description": "Steamed rice noodles, lightly tempered",
    "price": 50,
    "image": "/images/kinds/sevai.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 7
  },
  {
    "id": 9,
    "category_id": 2,
    "name": "Roast",
    "description": "Classic crisp roasted dosa",
    "price": 60,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 10,
    "category_id": 2,
    "name": "Onion Roast",
    "description": "Roasted dosa topped with fresh onions",
    "price": 70,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 11,
    "category_id": 2,
    "name": "Masal Roast",
    "description": "Roast dosa filled with spiced potato masala",
    "price": 80,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 12,
    "category_id": 2,
    "name": "Ghee Roast",
    "description": "Roast dosa finished with pure ghee",
    "price": 80,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 13,
    "category_id": 2,
    "name": "Onion Rava Roast",
    "description": "Crispy semolina roast loaded with onions",
    "price": 90,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 14,
    "category_id": 2,
    "name": "Ghee Masal Roast",
    "description": "Ghee roast filled with potato masala",
    "price": 100,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 15,
    "category_id": 2,
    "name": "Cashewnut Rava Roast",
    "description": "Semolina roast topped with roasted cashews",
    "price": 110,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 16,
    "category_id": 2,
    "name": "Uthappam",
    "description": "Thick savoury rice pancake",
    "price": 70,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 7
  },
  {
    "id": 17,
    "category_id": 2,
    "name": "Onion Uthappam",
    "description": "Uthappam topped with onions",
    "price": 80,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 8
  },
  {
    "id": 18,
    "category_id": 2,
    "name": "Tomato Uthappam",
    "description": "Uthappam topped with tomatoes",
    "price": 80,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 9
  },
  {
    "id": 19,
    "category_id": 2,
    "name": "Podi Uthappam",
    "description": "Uthappam with spiced gunpowder podi",
    "price": 80,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 10
  },
  {
    "id": 20,
    "category_id": 2,
    "name": "Ghee Uthappam",
    "description": "Uthappam finished with ghee",
    "price": 90,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 11
  },
  {
    "id": 21,
    "category_id": 2,
    "name": "Veg. Uthappam",
    "description": "Mixed vegetable topped uthappam",
    "price": 90,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 12
  },
  {
    "id": 22,
    "category_id": 2,
    "name": "Chappathi",
    "description": "Soft whole-wheat flatbread (2 pcs) with kurma",
    "price": 60,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 13
  },
  {
    "id": 23,
    "category_id": 2,
    "name": "Onion Chappathi",
    "description": "Chappathi stuffed with onions",
    "price": 70,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 14
  },
  {
    "id": 24,
    "category_id": 2,
    "name": "Parotta",
    "description": "Layered, flaky Kerala-style parotta (2 pcs)",
    "price": 60,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 15
  },
  {
    "id": 25,
    "category_id": 2,
    "name": "Kal Dosai",
    "description": "Thick, soft, slightly fermented dosa",
    "price": 70,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 16
  },
  {
    "id": 26,
    "category_id": 2,
    "name": "Elai Dosai",
    "description": "Traditional thick dosa cooked on banana leaf aroma",
    "price": 70,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 17
  },
  {
    "id": 27,
    "category_id": 3,
    "name": "Veg. Clear Soup",
    "description": "Light and clear mixed vegetable soup",
    "price": 70,
    "image": "/images/kinds/soup.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 28,
    "category_id": 3,
    "name": "Tomato Soup",
    "description": "Classic creamy tomato soup",
    "price": 70,
    "image": "/images/kinds/soup.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 29,
    "category_id": 3,
    "name": "Sweet Corn Soup",
    "description": "Sweet corn kernels in a mild veg broth",
    "price": 80,
    "image": "/images/kinds/soup.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 30,
    "category_id": 3,
    "name": "Mushroom Soup",
    "description": "Earthy mushroom soup, velvety texture",
    "price": 90,
    "image": "/images/kinds/soup.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 31,
    "category_id": 4,
    "name": "Veg. Cutlet",
    "description": "Crumb-fried mixed vegetable cutlets",
    "price": 100,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 32,
    "category_id": 4,
    "name": "Finger Chips",
    "description": "Crispy golden potato fingers",
    "price": 90,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 33,
    "category_id": 4,
    "name": "Paneer Pakoda",
    "description": "Deep fried gram-flour battered paneer fritters",
    "price": 130,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 34,
    "category_id": 4,
    "name": "Gobi 65",
    "description": "Spicy, tangy deep fried cauliflower florets",
    "price": 110,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 35,
    "category_id": 4,
    "name": "Mushroom 65",
    "description": "Crispy spiced deep fried mushrooms",
    "price": 130,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 36,
    "category_id": 4,
    "name": "Tomato Fry",
    "description": "Pan tossed spiced tomato fry",
    "price": 90,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 37,
    "category_id": 4,
    "name": "Masala Papad",
    "description": "Crisp papad topped with onion-tomato masala",
    "price": 60,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 38,
    "category_id": 4,
    "name": "Kuzhi Paniyaram",
    "description": "Steamed-fried savoury rice & lentil dumplings",
    "price": 90,
    "image": "/images/kinds/paniyaram.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 7
  },
  {
    "id": 39,
    "category_id": 4,
    "name": "Idiyappam & Appam",
    "description": "String hoppers and appam served together",
    "price": 90,
    "image": "/images/kinds/paniyaram.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 8
  },
  {
    "id": 40,
    "category_id": 5,
    "name": "Gobi Manchurian",
    "description": "Cauliflower florets tossed in tangy manchurian sauce",
    "price": 120,
    "image": "/images/kinds/manchurian.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 41,
    "category_id": 5,
    "name": "Chilly Gobi",
    "description": "Cauliflower tossed with chilli, capsicum & onion",
    "price": 120,
    "image": "/images/kinds/manchurian.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 42,
    "category_id": 5,
    "name": "Chilly Paneer",
    "description": "Paneer cubes tossed in spicy Indo-Chinese sauce",
    "price": 150,
    "image": "/images/kinds/manchurian.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 43,
    "category_id": 5,
    "name": "Chilly Mushroom",
    "description": "Mushrooms tossed in spicy chilli-garlic sauce",
    "price": 140,
    "image": "/images/kinds/manchurian.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 44,
    "category_id": 5,
    "name": "Soft Noodles",
    "description": "Wok tossed veg noodles",
    "price": 120,
    "image": "/images/kinds/noodles.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 45,
    "category_id": 5,
    "name": "Veg. Spl. Briyani (Chinese style)",
    "description": "Indo-Chinese style spiced veg biryani",
    "price": 150,
    "image": "/images/kinds/biryani.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 46,
    "category_id": 5,
    "name": "Chinees Briyani",
    "description": "Fragrant rice tossed with Chinese-style vegetables",
    "price": 150,
    "image": "/images/kinds/biryani.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 47,
    "category_id": 6,
    "name": "Paneer Butter Masala",
    "description": "Paneer cubes in a rich buttery tomato gravy",
    "price": 170,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 48,
    "category_id": 6,
    "name": "Green Peas Masala",
    "description": "Green peas simmered in a spiced onion-tomato gravy",
    "price": 130,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 49,
    "category_id": 6,
    "name": "Gobi Masala",
    "description": "Cauliflower cooked in a mildly spiced curry",
    "price": 130,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 50,
    "category_id": 6,
    "name": "Aloo Gobi Masala",
    "description": "Potato & cauliflower cooked with aromatic spices",
    "price": 130,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 51,
    "category_id": 6,
    "name": "Mushroom Masala",
    "description": "Mushrooms in a spiced curry gravy",
    "price": 140,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 52,
    "category_id": 6,
    "name": "Cheese Masala",
    "description": "Cottage cheese cubes in a creamy masala gravy",
    "price": 160,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 53,
    "category_id": 6,
    "name": "Malai Kofta",
    "description": "Fried vegetable & paneer dumplings in a creamy gravy",
    "price": 170,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 54,
    "category_id": 6,
    "name": "Mix. Veg Curry",
    "description": "Seasonal vegetables cooked in a mild curry",
    "price": 130,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 7
  },
  {
    "id": 55,
    "category_id": 6,
    "name": "Butter Paneer Masala",
    "description": "Paneer in a velvety butter-tomato gravy",
    "price": 180,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 8
  },
  {
    "id": 56,
    "category_id": 6,
    "name": "Aloo Butter Masala",
    "description": "Potatoes cooked in a rich buttery gravy",
    "price": 140,
    "image": "/images/kinds/curry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 9
  },
  {
    "id": 57,
    "category_id": 7,
    "name": "Naan",
    "description": "Soft, pillowy tandoor-baked leavened bread",
    "price": 50,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 58,
    "category_id": 7,
    "name": "Butter Naan",
    "description": "Naan brushed with butter",
    "price": 60,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 59,
    "category_id": 7,
    "name": "Roti",
    "description": "Whole wheat tandoor bread",
    "price": 40,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 60,
    "category_id": 7,
    "name": "Romali Roti",
    "description": "Ultra-thin soft handkerchief bread",
    "price": 50,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 61,
    "category_id": 7,
    "name": "Chola Poori",
    "description": "Fluffy fried poori served with chickpea masala",
    "price": 90,
    "image": "/images/kinds/poori.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 62,
    "category_id": 8,
    "name": "Veg. Fried Rice",
    "description": "Wok tossed rice with fresh vegetables",
    "price": 110,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 63,
    "category_id": 8,
    "name": "Veg. Pulao",
    "description": "Fragrant basmati rice cooked with mixed vegetables",
    "price": 120,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 64,
    "category_id": 8,
    "name": "Peas Pulao",
    "description": "Basmati rice cooked with green peas",
    "price": 120,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 65,
    "category_id": 8,
    "name": "Jeera Pulao",
    "description": "Basmati rice tempered with cumin",
    "price": 110,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 66,
    "category_id": 8,
    "name": "Mushroom Pulao",
    "description": "Basmati rice cooked with mushrooms",
    "price": 140,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 67,
    "category_id": 8,
    "name": "Kashmir Pulao",
    "description": "Mildly sweet pulao with fruits & nuts",
    "price": 150,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 68,
    "category_id": 8,
    "name": "Veg. Briyani",
    "description": "Classic spiced vegetable dum biryani",
    "price": 150,
    "image": "/images/kinds/biryani.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 69,
    "category_id": 8,
    "name": "Mushroom Briyani",
    "description": "Aromatic dum biryani with mushrooms",
    "price": 160,
    "image": "/images/kinds/biryani.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 7
  },
  {
    "id": 70,
    "category_id": 8,
    "name": "Curd Rice",
    "description": "Comforting curd rice tempered with mustard & curry leaves",
    "price": 80,
    "image": "/images/kinds/curdRice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 8
  },
  {
    "id": 71,
    "category_id": 8,
    "name": "Curd Semia",
    "description": "Vermicelli tossed in seasoned curd",
    "price": 80,
    "image": "/images/kinds/sevai.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 9
  },
  {
    "id": 72,
    "category_id": 8,
    "name": "Variety Rices",
    "description": "Assorted South Indian tamarind / lemon / coconut rice",
    "price": 90,
    "image": "/images/kinds/rice.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 10
  },
  {
    "id": 73,
    "category_id": 9,
    "name": "Cauliflower Roast",
    "description": "Whole roasted cauliflower in spiced masala",
    "price": 140,
    "image": "/images/kinds/roastDry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 74,
    "category_id": 9,
    "name": "Mushroom Roast",
    "description": "Pan roasted mushrooms in dry masala",
    "price": 150,
    "image": "/images/kinds/roastDry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 75,
    "category_id": 9,
    "name": "Paneer Masal Roast",
    "description": "Paneer roasted in a dry spiced masala",
    "price": 170,
    "image": "/images/kinds/roastDry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 76,
    "category_id": 9,
    "name": "Green Peas Masal Roast",
    "description": "Green peas roasted in a dry spiced masala",
    "price": 130,
    "image": "/images/kinds/roastDry.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 77,
    "category_id": 10,
    "name": "Set Dosa (Monday Special)",
    "description": "Soft mini dosas served in a stack of three",
    "price": 80,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 78,
    "category_id": 10,
    "name": "Peas Uthappam (Tuesday Special)",
    "description": "Uthappam topped with green peas",
    "price": 90,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 79,
    "category_id": 10,
    "name": "Five Taste Uthappam (Wednesday Special)",
    "description": "Uthappam topped with five signature toppings",
    "price": 100,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 80,
    "category_id": 10,
    "name": "Vanilla Roast (Thursday Special)",
    "description": "Signature house roast dosa",
    "price": 90,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 81,
    "category_id": 10,
    "name": "Adai - Aviyal (Friday Special)",
    "description": "Multi-lentil adai served with mixed vegetable aviyal",
    "price": 100,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 82,
    "category_id": 10,
    "name": "Chenna Masal Roast (Saturday Special)",
    "description": "Roast dosa filled with spiced chenna masala",
    "price": 100,
    "image": "/images/kinds/dosa.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 83,
    "category_id": 10,
    "name": "Veg Omelette (Sunday Special)",
    "description": "Besan-based vegetarian omelette",
    "price": 90,
    "image": "/images/kinds/uthappam.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 84,
    "category_id": 11,
    "name": "Chilly Parotta",
    "description": "Shredded parotta tossed with chilli & spices",
    "price": 130,
    "image": "/images/kinds/manchurian.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": true,
    "sort_order": 0
  },
  {
    "id": 85,
    "category_id": 11,
    "name": "Chilly Idly",
    "description": "Cubed idly tossed in spicy chilli sauce",
    "price": 100,
    "image": "/images/kinds/manchurian.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": true,
    "sort_order": 1
  },
  {
    "id": 86,
    "category_id": 11,
    "name": "Kaima Parotta",
    "description": "Parotta tossed with a rich, minced-vegetable style kaima masala",
    "price": 140,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 87,
    "category_id": 11,
    "name": "Peas Parotta",
    "description": "Shredded parotta tossed with green peas masala",
    "price": 130,
    "image": "/images/kinds/bread.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 88,
    "category_id": 11,
    "name": "Idly Fry",
    "description": "Pan fried idly tossed with spices",
    "price": 90,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 89,
    "category_id": 11,
    "name": "Gobi Fry",
    "description": "Dry roasted spiced cauliflower fry",
    "price": 110,
    "image": "/images/kinds/starter.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 90,
    "category_id": 12,
    "name": "Bournvita",
    "description": "Hot malted chocolate drink",
    "price": 50,
    "image": "/images/kinds/hotDrink.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 91,
    "category_id": 12,
    "name": "Ragimalt",
    "description": "Traditional finger-millet health drink",
    "price": 60,
    "image": "/images/kinds/hotDrink.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 92,
    "category_id": 12,
    "name": "Lemon Tea",
    "description": "Refreshing hot lemon tea",
    "price": 40,
    "image": "/images/kinds/hotDrink.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 93,
    "category_id": 12,
    "name": "Sukku Coffee",
    "description": "Traditional dry ginger coffee",
    "price": 50,
    "image": "/images/kinds/hotDrink.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 94,
    "category_id": 12,
    "name": "Kalkandu Milk",
    "description": "Milk sweetened with rock candy",
    "price": 60,
    "image": "/images/kinds/coldDrink.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 95,
    "category_id": 12,
    "name": "Badam Milk",
    "description": "Chilled milk infused with almonds & saffron",
    "price": 80,
    "image": "/images/kinds/coldDrink.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 96,
    "category_id": 13,
    "name": "Mini Cone",
    "description": "Bite sized crunchy cone",
    "price": 30,
    "image": "/images/kinds/iceCreamCone.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 97,
    "category_id": 13,
    "name": "Suvai Ball",
    "description": "Classic ice cream ball",
    "price": 40,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 98,
    "category_id": 13,
    "name": "Sunday Sundae",
    "description": "Layered sundae with toppings",
    "price": 90,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 99,
    "category_id": 13,
    "name": "Cassata Slice",
    "description": "Tri-colour cassata ice cream slice",
    "price": 60,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 100,
    "category_id": 13,
    "name": "Malai Kulfi",
    "description": "Traditional creamy malai kulfi",
    "price": 60,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 101,
    "category_id": 13,
    "name": "Super Cone",
    "description": "Large classic ice cream cone",
    "price": 50,
    "image": "/images/kinds/iceCreamCone.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 102,
    "category_id": 13,
    "name": "Premium Cassata",
    "description": "Rich premium cassata ice cream",
    "price": 80,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 103,
    "category_id": 13,
    "name": "Amrit Kalash Kulfi",
    "description": "Signature rich dry-fruit kulfi",
    "price": 90,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": true,
    "is_new": false,
    "sort_order": 7
  },
  {
    "id": 104,
    "category_id": 13,
    "name": "Italian's Touch",
    "description": "Italian style gourmet ice cream",
    "price": 100,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 8
  },
  {
    "id": 105,
    "category_id": 13,
    "name": "Melting Moments",
    "description": "Soft melt-in-mouth ice cream treat",
    "price": 80,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 9
  },
  {
    "id": 106,
    "category_id": 13,
    "name": "Phata Phat",
    "description": "Fun crackling-topped ice cream novelty",
    "price": 70,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 10
  },
  {
    "id": 107,
    "category_id": 14,
    "name": "Choc-O-Bar",
    "description": "Classic chocolate coated vanilla stick",
    "price": 40,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 108,
    "category_id": 14,
    "name": "Mini Chocobar",
    "description": "Bite sized chocolate coated stick",
    "price": 25,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 109,
    "category_id": 14,
    "name": "Nutty Chocobar",
    "description": "Chocolate coated stick with crunchy nuts",
    "price": 50,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 110,
    "category_id": 14,
    "name": "Mango Duo",
    "description": "Two layered mango ice cream stick",
    "price": 45,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 111,
    "category_id": 14,
    "name": "Raspberry Duo",
    "description": "Two layered raspberry ice cream stick",
    "price": 45,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 112,
    "category_id": 14,
    "name": "Orange Duo",
    "description": "Two layered orange ice cream stick",
    "price": 45,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 113,
    "category_id": 14,
    "name": "Fiesta",
    "description": "Colourful fruit-flavoured ice cream stick",
    "price": 50,
    "image": "/images/kinds/iceCreamStick.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 114,
    "category_id": 15,
    "name": "Cassatta",
    "description": "Classic tri-flavour ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 0
  },
  {
    "id": 115,
    "category_id": 15,
    "name": "Vanilla",
    "description": "Rich and creamy vanilla ice cream",
    "price": 50,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 1
  },
  {
    "id": 116,
    "category_id": 15,
    "name": "Strawberry",
    "description": "Fresh strawberry ice cream",
    "price": 55,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 2
  },
  {
    "id": 117,
    "category_id": 15,
    "name": "Pista Green",
    "description": "Roasted pistachio ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 3
  },
  {
    "id": 118,
    "category_id": 15,
    "name": "Mango",
    "description": "Seasonal mango ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": true,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 4
  },
  {
    "id": 119,
    "category_id": 15,
    "name": "Chocolate",
    "description": "Rich Belgian style chocolate ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 5
  },
  {
    "id": 120,
    "category_id": 15,
    "name": "Butter Scotch",
    "description": "Caramelised butterscotch ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 6
  },
  {
    "id": 121,
    "category_id": 15,
    "name": "Black Currant",
    "description": "Tangy black currant ice cream",
    "price": 60,
    "image": "/images/kinds/iceCreamScoop.jpg",
    "is_available": true,
    "is_popular": false,
    "is_chef_recommended": false,
    "is_new": false,
    "sort_order": 7
  }
];

export const defaultSettings = {
  "id": 1,
  "restaurant_name": "Amutha Surabi Restaurant",
  "tagline": "Experience Authentic Taste",
  "logo": "",
  "banner": "",
  "address": "8A, Thadagam Main Road, Edayar Palayam Junction, Coimbatore - 25",
  "phone": "",
  "opening_hours": "7:30 AM - 10:30 PM",
  "facebook": "",
  "instagram": "",
  "whatsapp": "",
  "theme_primary": "#D4AF37",
  "theme_dark": "#0B0B0F",
  "menu_url": "http://localhost:5173"
};
